### ISSUE TITLE
change 6ng/ul to 2ng/ul

### ISSUE THREAD

**Issue by hyacynth** [stanford-ssi/tdt-characterization#10]
in the part where you mention you'll be sending stocks to pan at 6ng/ul, it's actually 2ng/ul bc you dilute with 20 ul water first

**Comment by biosafetylvl5** [comment]
Fixed with 84b23b8b51ca98259a0717ff2bb77a9ec83b66bb

**Comment by hyacynth** [comment]
thanks for adding extra clarification to the end, but i was referring specifically to this line in the overview: "For PAN analysis, we will be sending in Terminal Deoxynucleotidyl Transferase extended samples with a concentration of 6ng/uL." which still has the wrong concentration listed
