### ISSUE TITLE
pan vs. gel comparison

### ISSUE THREAD

**Issue by hyacynth** [stanford-ssi/tdt-characterization#11]
so i checked the math for being able to run these samples on gels when we're done--gels are usually run on samples with 8ng/ul concentration DNA (so we can get ~20ng into a gel lane), and the samples you're saving for gel runs are 6ng/ul final concentration, which should be totally fine for gel running. (we can always load all 10 uL of sample + loading buffer mix instead of 5 if we get bands that are really faint). sorry for making such a big deal about this yesterday lol

**Comment by biosafetylvl5** [comment]
Fixed with commit 84b23b8b51ca98259a0717ff2bb77a9ec83b66bb
