### ISSUE TITLE
volume in 96well

### ISSUE THREAD

**Issue by hyacynth** [stanford-ssi/tdt-characterization#3]
highly recommend making the volumes in the 96well plates at least 50ul, or pipette mixing really really well (with small volumes effect of evaporation will become much more apparent, and it's harder to mix around)

**Comment by biosafetylvl5** [comment]
Do we _really_ want to almost triple our reaction volumes? We're already using so much TdT, among other things

**Comment by hyacynth** [comment]
hmmm, i agree but i can almost guarantee 15ul won’t be enough for 96 well plate. maybe if we find some 384 well plates we can run the 15ul reactions in those and mix really well and then transfer 10ul over to 96well plates with 20ul water in them for pan? that’s the best solution i can come up with

**Comment by biosafetylvl5** [comment]
Could we cover with parafilm? I feel like we're going to lose more volume by pipetting back and forth between plates, and it would be a terrible time pipetting 96 samples, something that increases chances of sample mixup

**Comment by biosafetylvl5** [comment]
Nope!
See slack, moving to *60uL*

**Comment by biosafetylvl5** [comment]
We're going with 30uL reaction volumes - anyone opposed? If not, I'm going to close this issue tonight.
