### ISSUE TITLE
internal controls

### ISSUE THREAD

**Issue by hyacynth** [stanford-ssi/tdt-characterization#5]
after everything in the reaction is stopped, we should add some <20nt strand (i'm thinking like 15mer from custom ladder, or some 6mer) in a 1:2 molar ratio (half the final concentration of BS_Start in the sample) and ~90nt strand (we have an oligo called 90-Mer) in a 2:1 molar ratio (twice the final concentration of BS_Start) to every well as an internal standard (only if pan tells us they don't add their own), so we have both a way to measure length within a lane and quantity within a lane, and make them comparable to other lanes

**Comment by hyacynth** [comment]
thanks for adding--can we reduce the total volume made of this? we only really need 20*96 ul = 1920 ul ~2 ml of this. we can make 2ml and still have some extra without going over by 800 uL (plus we'd have to use a falcon tube instead of being able to use a 2 ml tube to mix this). also, are we going with the same final amount (2ng/ul) of both control bands? might be safer to have the two bands be different concentrations so we can determine how accurate our quantitation is (and map the intensity units to real ng/ul units as accurately as possible)

**Comment by biosafetylvl5** [comment]
Change internal standard concentrations to check variable quantitation

**Comment by hyacynth** [comment]
new concentrations in stock solution are .75 ng/ul 8mer (6.28 ul of 100 mM 2387 g/mol 8mer), 1.5 ng/ul 15mer (6.52 ul of 100 mM 4601 g/mol 8mer), and 3 ng/ul 90mer (2.159 ul of 100 mM 27785 g/mol 90mer) in 2 mL total volume. this results in .5 ng/ul 8mer, 1 ng/ul 15mer, and 2 ng/ul 90mer in final sample sent to PAN. (assuming 15uL reaction volumes, change if we are upping the volume)

**Comment by biosafetylvl5** [comment]
Can you check my most recent changes and see if they fix things sufficiently?

**Comment by hyacynth** [comment]
uhhhhhh what happened to adding them to the 96well plate? that section is just gone lol

**Comment by hyacynth** [comment]
should be good now
