### ISSUE TITLE
dATP dilutions

### ISSUE THREAD

**Issue by hyacynth** [stanford-ssi/tdt-characterization#7]
in the instructions for the first dilution steps for dATP to 1 mM and 0.1 mM, i'd specify how much volume of the 10 mM stock to put into how much volume of water, not just the final volume/concentration. would make it easier for people doing the experiment

**Comment by biosafetylvl5** [comment]
Fixed with cefef1d7edb8c27ef6332621f8273033909b44ba

**Comment by hyacynth** [comment]
this still hasn't been fixed (also kinda confused as to what "100 uL of .1 mM, making at least 197 ul" means?)--would be more helpful during the experiment to know what volume of 10 mM to add to what volume of water to get the desired concentration, no matter what final volume is...
also, why are we making .1 mM and 1 mM solution separately instead of doing a serial dilution?

**Comment by biosafetylvl5** [comment]
See line number 3 - missed issue
