### ISSUE TITLE
check math on last two dATP dilutions (G and H)

### ISSUE THREAD

**Issue by hyacynth** [stanford-ssi/tdt-characterization#8]
they seem to be off by a factor of 10--you want 20:1 dATP to DNA ratio in one of them (G), but i calculated it and what you have now will give you 4:1 ratio. maybe you forgot to account for the new stock concentration somewhere in the code? i would just double check the math anyway, since it seems like for the molar ratios you listed in the table, you can do everything with 1 mM stock and shouldn't even need a .1 mM working stock at all... (would still recommend making one, though, and just multiplying pipetting volume by a factor of 10 if possible)

**Comment by biosafetylvl5** [comment]
Fixed with cefef1d7edb8c27ef6332621f8273033909b44ba
